### ISSUE TITLE
Effect on Each Piece!

### ISSUE THREAD

**Issue by reactwindd** [Heisenburger69/BurgerCustomArmor#35]
Example
```
Effect:
   helmet: 
      health_boost: 10
   chestplate:
      health_boost: 17.5 #impossible but that's what I get :/
   leggings:
      health_boost: 15
   boots:
      health_boots: 7.5 #same as the chestplate xD
```
